### ISSUE TITLE
Issue #01 - Wiki Home Page

### ISSUE THREAD

**Issue by keginzburg** [jacobbenowitz/5000px#1]
# Wiki Home Page
- [X] Is the first page you see upon entering the wiki
- [X] Contains a welcome message
- [X] Contains a link/placeholder for a link to the live page
- [X] All links in the right sidebar should contain each wiki page and link to the correct page
- [X] Correctly formatted
  - [X] each wiki page is listed in bullet points
  - [X] all links route the correct page
  
 ## Comments
 This looks great so far.

**Comment by jacobbenowitz** [comment]
Thank you Kyle!
