### ISSUE TITLE
Issue #02 - MVP List

### ISSUE THREAD

**Issue by keginzburg** [jacobbenowitz/5000px#2]
# MVP List
- [x] Should have 7 MVPs.
  - [X] 3 of those are User Auth, Heroku, and Production README.
  - [X] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [X] Includes two to three detailed bullets on functionality and presentation of feature
- [X] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [X] Estimates how long it will take the code each MVP
- [X] Correctly formatted
  - [X] MVPs are listed in an ordered list
  - [X] Each MVP is broken down into bullet points

## Comments
Production README can honestly go last as it is the last thing you’ll devote your limited time to.
Also, remember you only have 14 full days. Following the max estimates of your time, you’re currently hitting 14.5 days worth and that’s without the Comments as a main MVP.

1. User Auth MVP
    1. Add Splash Page Header Title; Splash Page is generally styling, with most functionality pointing to User Auth, so we usually consider Splash/User Auth together.
    2. Also add error handling bullet to User Auth
    3. Remove the “User can create an account with Google” bullet. This is ambitious and a great idea, but would be better suited as a Bonus down the line.
    4. Also, please merge User Accounts’ bullets (”User can edit their account details...”) to Profile Page MVP as it relates directly to that MVP’s CRUD cycle.
2. ESSENTIALS
    1. This section sounds mostly presentational; I think this is mostly styling, so I don’t know if I would count it as an MVP. Honestly, this section details things you’ll have to fold into other MVPs as you complete them. However, if it helps you with planning, then you’re welcome to keep it, but you should be sure to factor that time into other MVPs.
3. POST PICTURES
    1. Do you think you can get this done in 1 day?
4. LANDING PAGE
    1. Definitely incorporate the User Home Feed, along with Featured Photographers and Explore the Community (Editor’s Choice/Featured Galleries). Quests and Resource Hub might be a bonus for the Home Feed down the line as they fall in the same area as Galleries and Discover.
    2. You’ll probably fold a lot of the bullets from Essentials into this section.
    3. Do you need 4 full days for this?
5. COMMENTS
    1. I would refactor this MVP into a bonus as well and honestly make it the first bonus you set for yourself. It might take more than a day, but it’s definitely going to add a lot of community atmosphere to your site.

**Comment by jacobbenowitz** [comment]
Thank you for your detailed feedback. I have updated the MVP List and addressed all of your points. Please review when you have a moment.

**Comment by keginzburg** [comment]
Looks solid!
