### ISSUE TITLE
Issue #04 - Sample State

### ISSUE THREAD

**Issue by keginzburg** [jacobbenowitz/5000px#4]
# Sample State
- [X] State shape is flat!
- [X] State’s keys are camelCased
- [X] All keys within the values in the state are accessible in the schema
- [X] Correctly formatted
  - [X] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
  - [X] Top level slices
    - [X] `entities`
    - [X] `session`
    - [X] `errors` (here or in `ui`)
    - [X] `ui` (if needed)
  - [X] Should NOT have nested slices, aka `comments` inside of `posts`
   + Some info from other tables is ok, for instance:
    + the author username and imageurl for a post. basically any info that the user can’t change
    + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments
What are you planning to do with your allUsers, allPhotos, etc key-value pairs in each slice of state?

If you nix userPhotos and userProfiles joins tables, then we can remove this from sample state.

**Comment by jacobbenowitz** [comment]
@keginzburg , please see my notes below:
- allUsers, allProfiles, userPhotos: removed, necessary
- allPhotos: indicates ordering for PhotosIndex/Home Feed (recent photos shown earlier in feed)
  - should I just order by 'createdAt'?
- allComments: indicates ordering for CommentsIndex on PhotoShow component
  - should I just order by 'createdAt'?
- userProfiles: keeping, needed to fetch profile data for the ProfileShow component

**Comment by keginzburg** [comment]
Via your allPhotos and allComments slices, you're only adding the keys for those photo and comment objects, so it's a matter of how you intend to use those primary key ids. Using createdAt could be useful. There's also the matter that recent photos might just be given the latest primary key id (out of 4 photos in your backend, 4 is more recent than 1 technically). Something to look into. Sounds good though.

**Comment by jacobbenowitz** [comment]
Thanks for the feedback, I will try and use them for ordering. If I do not end up using them I'll be sure to remove them from the state!
