### ISSUE TITLE
Issue #05 - Backend Routes

### ISSUE THREAD

**Issue by keginzburg** [jacobbenowitz/5000px#5]
# Backend Routes
- [X] Contains the following sections: HTML, API Endpoints(Backend)
- [X] Each route has a description
- [X] API Endpoint routes contains wildcard variables written in `snake_case`
- [X] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [X] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
  + probably doesn’t need a `GET likes` api endpoint because that info comes through the post show

## Comments
Users

1. Do you need a backend route for getting the data for one user at a time?

General

1. Food for thought: will there be any custom backend routes necessary for your implementation of this clone or maybe bonuses?

**Comment by jacobbenowitz** [comment]
@keginzburg  Updates pushed, notes below:

_Users_
_Do you need a backend route for getting the data for one user at a time?_
- Oops! Yes of course, added.
- Also added profiles routes (CRUD)

_General
Will there be any custom backend routes necessary for your implementation of this clone or maybe bonuses?_
- Added comments routes (CRUD)
