### ISSUE TITLE
Issue #06 - Frontend Routes & Components

### ISSUE THREAD

**Issue by keginzburg** [jacobbenowitz/5000px#6]
# Frontend Routes
- [X] Frontend routes contains wildcard variables written in `camelCase`
- [X] Correctly formatted
  - [X] Routes are displayed with `inline coding text` (backticks)

## Comments
When Logged Out

1. I believe you need your /login route here instead of When Logged In

When Logged In

1. I see that the splash page and the general home page both have a path of /. Most sites usually redirect to a /home or /feed after logging in, but this should be fun to render with your components.
2. Do we need a  /photos/new path for a Photos Form when we already have a /photos/upload path and UploadForm. What is the difference between these two?

General

1. Keep in mind you might integrate /galleries in the future.

**Comment by jacobbenowitz** [comment]
Hi @keginzburg , updated frontend routes with your feedback and notes are below: 

_When Logged Out_
- added `/login` route :)

_When Logged In_
- _splash page and the general home page both have a path of `/`_
  - Understood. The actual 500px site has the `/` route for both the landing page and the home feed for logged-in users, so I decided to replicate that structure.

_Do we need a /photos/new path for a Photos Form when we already have a /photos/upload path and UploadForm?_
- In second thought, no... but there are two forms. Updated both components to be under the `/photos/upload` path:
  - The first form is only for uploading the image (drag and drop/select file):
![CleanShot 2022-04-21 at 15 14 57](https://user-images.githubusercontent.com/49706068/164536353-dd1800d2-d04c-45c4-96ec-bdbfd7e96a08.png)
  - The second form in for adding the photo details:
![CleanShot 2022-04-21 at 15 15 48](https://user-images.githubusercontent.com/49706068/164536441-4b11f926-bae1-40ac-9243-cb56fac677f8.png)

_Keep in mind you might integrate /galleries in the future._
- Good point, added galleries routes:
  - `/profiles/:userId/galleries` 
  - `/profiles/:userId/galleries/:galleryId`

**Comment by keginzburg** [comment]
I see how they go about that now. I think you could do it either way. Using two components that we know will work in tandem under one route might be fine.
